function [deltaP]=calculDeltaP(ordre, D)
% fonction qui calcule la différence de distance induite par une
% permutation sur toutes les permutations possibles. La valeur à une case
% i,j donne la différence si on permute la ville i et la ville j
    s=size(ordre,2); % nombre de villes
    deltaP = zeros(s);

    % exception : permutation entre la première et dernière ville
    deltaP(ordre(1),ordre(s)) =  D(ordre(s)+1, ordre(2)+1) ...
                            - D(ordre(1)+1, ordre(2)+1) ...
                            + D(ordre(s-1)+1, ordre(1)+1) ...
                            - D(ordre(s-1)+1, ordre(s)+1);
    deltaP(ordre(s),ordre(1)) = deltaP(ordre(1),ordre(s));
    for k = 2:s-1
        deltaP(ordre(1),ordre(k)) =  (D(ordre(k)+1, ordre(2)+1) + D(ordre(k)+1, 1)) ...
                            - (D(ordre(1)+1, ordre(2)+1) + D(ordre(1)+1, 1)) ...
                            + D(ordre(k-1)+1, ordre(1)+1) + D(ordre(k+1)+1, ordre(1)+1) ...
                            - (D(ordre(k-1)+1, ordre(k)+1) + D(ordre(k+1)+1, ordre(k)+1));
        deltaP(ordre(k),ordre(1)) = deltaP(ordre(1),ordre(k));
    end

    for k = 2:s-1
        deltaP(ordre(k),ordre(s)) =  (D(ordre(s-1)+1, ordre(k)+1) + D(ordre(k)+1, 1)) ...
                                - (D(ordre(s-1)+1, ordre(s)+1) + D(ordre(s)+1, 1)) ...
                                + D(ordre(k-1)+1, ordre(s)+1) + D(ordre(k+1)+1, ordre(1)+1) ...
                                - (D(ordre(k-1)+1, ordre(k)+1) + D(ordre(k+1)+1, ordre(k)+1));
        deltaP(ordre(s),ordre(k)) = deltaP(ordre(k),ordre(s));
        for l = k+1:s-1
            deltaP(ordre(k),ordre(l)) =  (D(ordre(l)+1, ordre(k+1)+1) + D(ordre(l)+1, ordre(k-1)+1)) ...
                                - (D(ordre(k)+1, ordre(k+1)+1) + D(ordre(k)+1, ordre(k-1)+1)) ...
                                + D(ordre(l-1)+1, ordre(k)+1) + D(ordre(l+1)+1, ordre(k)+1) ...
                                - (D(ordre(l-1)+1, ordre(l)+1) + D(ordre(l+1)+1, ordre(l))+1);
            deltaP(ordre(l),ordre(k)) = deltaP(ordre(k),ordre(l));
        end
    end
end